name: swalf
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bot_toast:
  cached_network_image:
  connectivity_plus:
  country_code_picker:
  cupertino_icons:
  dio:
  dartz:
  easy_localization:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_secure_storage: 9.0.0
  flutter_svg:
  flutter_screenutil:
  get_it:
  go_router:
  google_fonts: 6.1.0
  injectable:
  logger:
  rxdart:
  shared_preferences:
  shimmer: ^3.0.0
  url_launcher:
  lottie: ^2.7.0
  pinput: ^3.0.1
  local_auth: ^2.1.8
  file_picker: ^6.1.1
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  google_maps_flutter: ^2.5.3
  geolocator:
  permission_handler: ^11.2.0
  image_picker: ^1.0.8
  image_cropper:
  device_info_plus: ^9.1.1
  pin_code_fields: ^8.0.1
  flutter_animate: ^4.5.0
  share_plus: ^7.2.2
  animated_bottom_navigation_bar: ^1.3.3
  infinite_scroll_pagination: ^4.0.0
  readmore: ^3.0.0
  flutter_multi_formatter: ^2.12.4
  dotted_border: ^2.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  pusher_channels_flutter: ^2.2.1
  # pusher_client:
  #   git:
  #     url: https://github.com/eng-sayed/pusher_client.git  

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  injectable_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_gen:
  output: lib/core/resources/gen/
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/lang/